source 'https://github.com/CocoaPods/Specs.git'
target 'SnoozeLocalNotification', :exclusive => true do
  pod "SnoozeLocalNotification", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SnoozeLocalNotification", :path => "../"

  pod 'Kiwi'
end
