language: objective-c
before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/SnoozeLocalNotification.xcworkspace -scheme SnoozeLocalNotification -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
